### ISSUE TITLE
ShopsController, element requis erreur

### ISSUE THREAD

**Issue by farzim** [MrSaooty/ExtazCMS#17]
Une erreur ce produit lors de l'achat d'un élément dans la boutique ou son ajout pour la version 1.4 du CMS (qui d'ailleurs est identifié comme 1.5 dans le footer).

Dans /app/Controller/ShopsController.php ligne 292, la condition verifie si l'element a un prerequis avec: $item['Shop']['required'] != -1
Hors, lors de l'ajout d'un élément a la boutique, il n'y a pas de demande concernant le(s) prérequi(s) et est donc enregistré dans la BDD avec un valeur NULL (non -1) !

**Comment by MrSaooty** [comment]
Salut dans le footer c'est bien noté 1.4 j'ai vérifié donc je sais pas si tu as bien téléchargé la 1.4, tu as peut-être téléchargé la pre release de la 1.5.

Concernant le problème évoqué, lors de l'ajout d'un élément dans la boutique, il y a bien une demande concernant le(s) prérequi(s).
![](http://img.prntscr.com/img?url=http://i.imgur.com/z9HqXeC.png)
Lorsque j'ajoute un élément dans la boutique le champs required est bien a -1, même si je ne sellectionne pas de prérequis.

**Comment by farzim** [comment]
Le fichier télécharger était celui marqué comme version 1.4 (la 1.5 n'etant pas disponible depuis GitHub de plus).

Pour l'ajout d'élément à la boutique, voici ce que j'ai moi contrairement à vous: http://i.imgur.com/SrrjcnK.png

**Comment by MrSaooty** [comment]
Biensur que si... la 1.5 est disponible depuis GitHub sinon ou est l’intérêt ?

Bref tu n'a tout simplement pas la bonne version du projet je pense.
