### ISSUE TITLE
A quoi sert

### ISSUE THREAD

**Issue by Nicocraft71** [MrSaooty/ExtazCMS#19]
A quoi sert le bouton Ajouter ami et Envoyer message sur le profil d'un joueur ?
On ne peut pas cliquer dessus

**Comment by MrSaooty** [comment]
Oui ces boutons sont désactivés car les features ne sont pas encore développé, ça permet de remplir un peu la page profil.

**Comment by Nicocraft71** [comment]
C'est prévu pour dans longtemps ? :)

**Comment by MrSaooty** [comment]
Le projet est arrêté http://www.bukkit.fr/topic/15381-extazcms-un-v%C3%A9ritable-site-pour-votre-serveur-minecraft-gratuit-open-source/page-49#entry222848

**Comment by Nicocraft71** [comment]
Ah ok dommage

**Comment by Nicocraft71** [comment]
Désolé de réouvrir mais, si on apporte des nouveautés sur github, tu les accepteras ?

**Comment by MrSaooty** [comment]
Tout est noté sur le post que j'ai écris

**Comment by Nicocraft71** [comment]
Ah ok, dommage qu'il s'arrête au moment ou je le connais, bonne continuation :/

**Comment by MrSaooty** [comment]
Merci

**Comment by Nicocraft71** [comment]
Bon désolé de reposté mais, ça serai sympa de faire un poste qui expliquer un peu comment marche ton code pour ceux qui veulent le reprendre

**Comment by MrSaooty** [comment]
Non

**Comment by Nicocraft71** [comment]
Ok ._.

**Comment by MrSaooty** [comment]
Je pense que t'as pas lu le post sur le forum ;)

**Comment by Nicocraft71** [comment]
Si si, mais ça serai sympa d'expliquer un peu ton code pour ceux qui veulent le reprendre ._.

**Comment by MrSaooty** [comment]
Encore une fos je pense que tu n'a pas lu le post

**Comment by Nicocraft71** [comment]
Et juste tu parles d'une version finale, tu ajouteras quelque nouveautés ?

**Comment by Nicocraft71** [comment]
Car je pense que si tu finis juste ami et message ton cms sera complet :/
